---
- name: Insert Error Message Info into MySQL DB
  hosts: all
  become: yes
  vars:
    db_host: "mysql-db.aiops.svc.cluster.local"
    db_user: "mysql"
    db_pass: "redhat"
    db_name: "aiopsdb"
    server_name: "bastion.wkq7q.sandbox2937.opentlc.com"
    error_msg: "Nginx service is not running."
    status_msg: "Open"
    # This will be dynamically templated during playbook execution
    sql_insert_template: >
       INSERT INTO Error_Table (Error_Message, Server_Name, Status) 
       VALUES ('{{ error_msg }}', '{{ server_name }}', '{{ status_msg }}');
    sql_select_template: >
       SELECT COUNT(*) FROM Error_Table 
       WHERE LOWER(Server_Name) = LOWER('{{ server_name }}') AND LOWER(Error_Message) = LOWER('{{ error_msg }}')
       AND created_at >= NOW() - INTERVAL 1 HOUR;
     
  tasks:
    - name: Ensure MySQL Shell (mysqlsh) is installed
      ansible.builtin.package:
        name: mysql-shell
        state: present

    - name: Check if the Server Name & Error already exist
      ansible.builtin.shell: |
        mysqlsh --sql -h {{ db_host }} -u {{ db_user }} -p{{ db_pass }} --schema {{ db_name }} --execute "{{ sql_select_template }}"
      register: duplicate_check
        
    - name: Show found status
      debug:
        msg: "Error already exists for the server {{ server_name }}"
      when: duplicate_check.stdout | int > 0
      
    - name: Insert entry into MySQL database
      ansible.builtin.shell: |
        mysqlsh --sql -h {{ db_host }} -u {{ db_user }} -p{{ db_pass }} --schema {{ db_name }} --execute "{{ sql_insert_template }}"
      when: duplicate_check.stdout | int == 0
