---
- name: Ensure Nginx is running
  hosts: all
  become: true
  tasks:
    - name: Check Nginx status
      systemd:
        name: nginx
        state: started
      register: nginx_status

    - name: Start Nginx if not running
      systemd:
        name: nginx
        state: started
      when: nginx_status.status.ActiveState != "active" or nginx_status.status.SubState != "running"
      register: start_nginx

    - name: Display Start Result
      debug:
        msg: "Nginx started successfully"
      when: start_nginx.changed
