---
- name: Ensure Nginx is running
  hosts: all
  become: true
  tasks:
    - name: Check Nginx service status
      systemd:
        name: nginx
        state: started
      register: nginx_status

    - name: Start Nginx service if not running
      systemd:
        name: nginx
        state: started
      when: nginx_status.status.ActiveState != "active"
      register: nginx_start

    - name: Display result of Nginx start
      debug:
        msg: "Nginx started successfully."
      when: nginx_start.changed

    - name: Display that Nginx was already running
      debug:
        msg: "Nginx was already running."
      when: not nginx_start.changed and nginx_status.status.ActiveState == "active"

    - name: Display Error of Nginx start
      debug:
        msg: "Error Starting Nginx"
      when: nginx_start.failed
