---
- hosts: all
  become: true
  tasks:
    - name: Check Nginx service status
      systemd:
        name: nginx
        state: running
      register: nginx_status
      ignore_errors: true

    - name: Start Nginx service if not running
      systemd:
        name: nginx
        state: started
      when: nginx_status.status.ActiveState != "active"
      retries: 3
      delay: 5
