---
- name: Ensure Nginx is running
  hosts: all
  become: true
  tasks:
    - name: Check Nginx status
      systemd:
        name: nginx
        state: started
        enabled: true
      register: nginx_status

    - name: Start Nginx if not running
      systemd:
        name: nginx
        state: started
        enabled: true
      when: nginx_status.status.ActiveState != "active" or nginx_status.status.ActiveState is undefined
