---
- name: Ensure Nginx is running
  hosts: all
  become: true
  tasks:
    - name: Check Nginx status
      systemd:
        name: nginx
        state: started
        enabled: true
      register: nginx_status

    - name: Start Nginx if stopped
      systemd:
        name: nginx
        state: started
        enabled: true
      when: nginx_status.status.ActiveState != "active" or nginx_status.status.SubState != "running"

    - name: Display Nginx status
      debug:
        msg: "Nginx is now running."
      when: nginx_status.status.ActiveState != "active" or nginx_status.status.SubState != "running"
