- name: Ensure Nginx is running
  hosts: all  # Target all hosts or specify a group
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Check Nginx status
      systemd:
        name: nginx
        state: started
      register: nginx_status

    - name: Start Nginx service if not running
      systemd:
        name: nginx
        state: started
      when: nginx_status.status.ActiveState != "active"

    - name: Reload Nginx after start (optional, only if configuration needs to be applied)
      systemd:
        name: nginx
        state: reloaded
      when: nginx_status.status.ActiveState != "active" and nginx_status.status.LoadState == "loaded"

    - name: Display Nginx status
      debug:
        msg: "Nginx status: {{ nginx_status }}"

