---
- name: Ensure Nginx is running
  hosts: all
  become: true  # Required for service management

  tasks:
    - name: Check Nginx status
      systemd:
        name: nginx
        state: started
      register: nginx_status

    - name: Start Nginx if not running
      service:
        name: nginx
        state: started
      when: nginx_status.status.ActiveState != "active"

    - name: Display Nginx Status
      debug:
        msg: "Nginx status is: {{ nginx_status }}"
