- name: Ensure Nginx is running
  hosts: all
  become: true
  tasks:
    - name: Check Nginx status
      systemd:
        name: nginx
        state: started
      register: nginx_status

    - name: Start Nginx service if not running
      systemd:
        name: nginx
        state: started
      when: nginx_status.status.ActiveState != "active"

