---
- name: Ensure Nginx is running
  hosts: all
  become: true
  tasks:
    - name: Check Nginx service status
      systemd:
        name: nginx
        state: started
      register: nginx_status

    - name: Start Nginx service if stopped
      systemd:
        name: nginx
        state: started
      when: nginx_status.status.ActiveState != "active"
      notify:
        - Reload Nginx if changed

  handlers:
    - name: Reload Nginx if changed
      systemd:
        name: nginx
        state: reloaded
