---
- name: Check status
  hosts: all
  sources:
    - name: URL to check
      ansible.eda.url_check:
        urls:
          - http://bastion.wkq7q.sandbox2937.opentlc.com

  rules:
    - name: Insert Error Message Info into MySQL DB
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "DB Update"
          organization: "Default"
