---
- name: OpenShift Health Monitor
  hosts: localhost

  sources:
    - name: health_check_webhook
      ansible.eda.http
      parameters:
        port: 5000

  rules:
    - name: Trigger Email Alert on Failure
      condition: event.status == "failed"
      action:
        run_job_template:
          name: "OpenShift Health Alert"
          organization: "Default"
          extra_vars:
            check: "{{ event.checks_failed }}"
            status: "{{ event.status }}"
