---
- name: OpenShift Health Monitor
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        port: 5000

  rules:
    - name: CO degraded → trigger template
      condition: event.payload.status == "failed"
      action:
        run_job_template:
          name: "OpenShift Health Alert"
          organization: "Default"
