- name: OpenShift Health Monitor
  hosts: localhost
  sources:
    - name: oc_health_check_job
      ansible.eda.awx_event:
        job_template: "OpenShift Health Check"  # Your playbook as a Job Template
        organization: "Default"
        event: "job_completed"  # Trigger when job completes

  rules:
    - name: Trigger Alert Only on Failure
      condition: event.status == "failed"  # Only when the Job Template fails
      action:
        run_job_template:
          name: "OpenShift Health Alert"
          organization: "Default"
