- name: OpenShift Health Monitor
  hosts: localhost
  sources:
    - name: OpenShift CO/MCP/Node/Cert/Pods Check
      ansible.eda.execution_queue:
        playbook_path: playbooks/openshift_health_check.yml

  rules:
    - name: Trigger Alert on Failure
      condition: event.status == "failed"
      action:
        run_job_template:
          name: "OpenShift Health Alert"
          organization: "Default"
