---
name: pod-failure-alert
description: Trigger email alert for any pod not running in the cluster
hosts: localhost
vars:
  email_template_name: "OpenShift Health Alert"  # Your AAP template name

rules:
  - name: pod-not-running
    condition: >
      event.body.status is defined and event.body.status != "Running"
    actions:
      - name: trigger-email-template
        ansible.builtin.include_role:
          name: trigger-job-template
        vars:
          template_name: "{{ email_template_name }}"
          namespace: "{{ event.body.namespace | default('unknown') }}"
          pod_name: "{{ event.body.pod_name | default('unknown') }}"
          pod_status: "{{ event.body.status }}"
